services:
  - type: web
    name: deep-intelligence-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python minimal_server.py
    healthCheckPath: /health
    envVars:
      - key: PPLX_API_KEY1
        sync: false

